services:
  - type: web
    name: payguard-backend
    runtime: docker
    dockerfilePath: ./gigshield-backend/Dockerfile
    port: 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SeBqPSxLw5Aqz4
      - key: RAZORPAY_KEY_SECRET
        value: 8yoAgFKLalSU0o7vqKbsdVs4

  - type: web
    name: payguard-ml-service
    runtime: docker
    dockerfilePath: ./model/Dockerfile
    port: 8000

  - type: web
    name: payguard-mobile-web
    runtime: docker
    dockerfilePath: ./mobile/Dockerfile
    port: 80
