services:
  - type: web
    name: payguard-backend
    image: ghcr.io/triparnoxd/gigshield-backend:latest
    port: 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SeBqPSxLw5Aqz4
      - key: RAZORPAY_KEY_SECRET
        value: 8yoAgFKLalSU0o7vqKbsdVs4
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

  - type: web
    name: payguard-ml-service
    image: ghcr.io/triparnoxd/gigshield-ml:latest
    port: 8000

  - type: web
    name: payguard-mobile-web
    image: ghcr.io/triparnoxd/gigshield-mobile:latest
    port: 80
